# Generated by Django 4.2 on 2023-04-25 14:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('year_built', models.PositiveIntegerField(blank=True, null=True)),
                ('owners_manual', models.FileField(blank=True, null=True, upload_to='manuals/')),
            ],
        ),
        migrations.CreateModel(
            name='ApplianceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=14, null=True)),
                ('company', models.CharField(max_length=50)),
                ('street', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Flooring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(blank=True, max_length=150, null=True)),
                ('model', models.CharField(blank=True, max_length=150, null=True)),
                ('year', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlooringType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flooring_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('bathrooms', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('sq_footage', models.PositiveIntegerField(blank=True, null=True)),
                ('lot_size', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HomeFeatureArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_feature_area', to='househubapi.featurearea')),
                ('feature_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_feature_zone', to='househubapi.featurezone')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='househubapi.home')),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UtilityProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('street', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=14, null=True)),
                ('account_identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('plan_name', models.CharField(blank=True, max_length=100, null=True)),
                ('cost_per_month', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_utilities', to='househubapi.home')),
                ('utility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utility_service', to='househubapi.utility')),
            ],
        ),
        migrations.CreateModel(
            name='TileFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tile_material', models.CharField(blank=True, max_length=150, null=True)),
                ('tile_color', models.CharField(blank=True, max_length=100, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('thickness', models.FloatField(blank=True, null=True)),
                ('grout_type', models.CharField(blank=True, max_length=150, null=True)),
                ('grout_color', models.CharField(blank=True, max_length=150, null=True)),
                ('grout_make', models.CharField(blank=True, max_length=150, null=True)),
                ('grout_sealant', models.CharField(blank=True, max_length=150, null=True)),
                ('flooring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='househubapi.flooring')),
            ],
        ),
        migrations.CreateModel(
            name='SmokeDetector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('make', models.CharField(blank=True, max_length=200, null=True)),
                ('model', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('power_source', models.CharField(blank=True, max_length=200, null=True)),
                ('date_installed', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('lifespan', models.IntegerField(blank=True, null=True)),
                ('carbon_monoxide_detector', models.BooleanField()),
                ('manual', models.FileField(blank=True, null=True, upload_to='manuals')),
                ('home_feature_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='househubapi.homefeaturearea')),
            ],
        ),
        migrations.CreateModel(
            name='Roof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, max_length=150, null=True)),
                ('color', models.CharField(blank=True, max_length=150, null=True)),
                ('make', models.CharField(blank=True, max_length=150, null=True)),
                ('model', models.CharField(blank=True, max_length=150, null=True)),
                ('pitch', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('lifespan', models.IntegerField(blank=True, null=True)),
                ('solar_reflectance_index', models.IntegerField(blank=True, null=True)),
                ('installation_method', models.CharField(blank=True, max_length=250, null=True)),
                ('home_feature_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='househubapi.homefeaturearea')),
            ],
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('depth', models.FloatField(blank=True, null=True)),
                ('shape', models.CharField(blank=True, max_length=150, null=True)),
                ('material', models.CharField(blank=True, max_length=150, null=True)),
                ('heating_system', models.CharField(blank=True, max_length=250, null=True)),
                ('filtration_system', models.CharField(blank=True, max_length=100, null=True)),
                ('lighting', models.CharField(blank=True, max_length=100, null=True)),
                ('water_type', models.CharField(blank=True, max_length=100, null=True)),
                ('home_feature_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='househubapi.homefeaturearea')),
            ],
        ),
        migrations.CreateModel(
            name='Paint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paint_usage_description', models.CharField(blank=True, max_length=250, null=True)),
                ('make', models.CharField(blank=True, max_length=150, null=True)),
                ('model', models.CharField(blank=True, max_length=150, null=True)),
                ('finish', models.CharField(blank=True, max_length=150, null=True)),
                ('coverage', models.CharField(blank=True, max_length=150, null=True)),
                ('VOC_content', models.CharField(blank=True, max_length=150, null=True)),
                ('durability', models.CharField(blank=True, max_length=150, null=True)),
                ('color_retention', models.CharField(blank=True, max_length=150, null=True)),
                ('home_feature_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='househubapi.homefeaturearea')),
            ],
        ),
        migrations.CreateModel(
            name='Lighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lighting_usage_description', models.CharField(blank=True, max_length=250, null=True)),
                ('make', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('bulb_shape', models.CharField(blank=True, max_length=100, null=True)),
                ('wattage', models.FloatField(blank=True, null=True)),
                ('voltage', models.FloatField(blank=True, null=True)),
                ('lumens', models.FloatField(blank=True, null=True)),
                ('color_temperature', models.FloatField(blank=True, null=True)),
                ('color_description', models.CharField(blank=True, max_length=150, null=True)),
                ('lifespan', models.IntegerField(blank=True, null=True)),
                ('base_type', models.CharField(blank=True, max_length=150, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('home_feature_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='househubapi.homefeaturearea')),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='househubapi.home')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HomeContractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=14, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(max_length=50)),
                ('POC_name', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='househubapi.home')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contractor_specialty', to='househubapi.specialty')),
            ],
        ),
        migrations.CreateModel(
            name='HardwoodFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, max_length=150, null=True)),
                ('finish', models.CharField(blank=True, max_length=100, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('thickness', models.FloatField(blank=True, null=True)),
                ('hardness', models.FloatField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=150, null=True)),
                ('grade', models.CharField(blank=True, max_length=150, null=True)),
                ('installation_method', models.CharField(blank=True, max_length=150, null=True)),
                ('flooring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='househubapi.flooring')),
            ],
        ),
        migrations.CreateModel(
            name='Grass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=150, null=True)),
                ('home_feature_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='househubapi.homefeaturearea')),
            ],
        ),
        migrations.AddField(
            model_name='flooring',
            name='flooring_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='househubapi.flooringtype'),
        ),
        migrations.AddField(
            model_name='flooring',
            name='home_feature_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='househubapi.homefeaturearea'),
        ),
        migrations.CreateModel(
            name='FireExtinguisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('location_in_area', models.CharField(blank=True, max_length=250, null=True)),
                ('classification', models.CharField(blank=True, max_length=250, null=True)),
                ('size', models.FloatField(blank=True, null=True)),
                ('extinguishing_agent', models.CharField(blank=True, max_length=250, null=True)),
                ('range', models.FloatField(blank=True, null=True)),
                ('discharge_time', models.FloatField(blank=True, null=True)),
                ('certification', models.CharField(blank=True, max_length=100, null=True)),
                ('home_feature_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='househubapi.homefeaturearea')),
            ],
        ),
        migrations.CreateModel(
            name='Fence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('style', models.CharField(blank=True, max_length=150, null=True)),
                ('material', models.CharField(blank=True, max_length=150, null=True)),
                ('finish_manufacturer', models.CharField(blank=True, max_length=250, null=True)),
                ('finish_product', models.CharField(blank=True, max_length=100, null=True)),
                ('finish_color', models.CharField(blank=True, max_length=100, null=True)),
                ('home_feature_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='househubapi.homefeaturearea')),
            ],
        ),
        migrations.CreateModel(
            name='ContractorSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_info', to='househubapi.contractor')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialty_info', to='househubapi.specialty')),
            ],
        ),
        migrations.CreateModel(
            name='CarpetFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, max_length=150, null=True)),
                ('padding', models.CharField(blank=True, max_length=100, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('pile_height', models.FloatField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=150, null=True)),
                ('installation_method', models.CharField(blank=True, max_length=150, null=True)),
                ('flooring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='househubapi.flooring')),
            ],
        ),
        migrations.CreateModel(
            name='ApplianceWarranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warranty_type', models.CharField(blank=True, max_length=50, null=True)),
                ('issuer', models.CharField(max_length=250)),
                ('purchase_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('warranty_length', models.FloatField()),
                ('purchase_price', models.FloatField(blank=True, null=True)),
                ('warranty_documents', models.FileField(blank=True, max_length=250, null=True, upload_to='warranties/')),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='househubapi.appliance')),
            ],
        ),
        migrations.CreateModel(
            name='AppliancePurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('place_of_purchase', models.CharField(blank=True, max_length=250, null=True)),
                ('purchase_price', models.FloatField(blank=True, null=True)),
                ('receipt', models.FileField(blank=True, max_length=250, null=True, upload_to='receipts/')),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='househubapi.appliance')),
            ],
        ),
        migrations.CreateModel(
            name='ApplianceCustomFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_feature', models.CharField(max_length=50)),
                ('make', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('size', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliance_custom_features', to='househubapi.appliance')),
            ],
        ),
        migrations.AddField(
            model_name='appliance',
            name='appliance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_of_appliance', to='househubapi.appliancetype'),
        ),
        migrations.AddField(
            model_name='appliance',
            name='home_feature_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliance_in_area', to='househubapi.homefeaturearea'),
        ),
    ]
